### PR TITLE
Use PSR-7, change rule signature

### PR DESCRIPTION
**Pull request by barryvdh**
As discussed in https://github.com/phanan/kupo/issues/12#issuecomment-282981476

- Uses PSR-7 Response + Uri objects for the response + url to pass along.
- Moved the Crawler, Response and Uri to the check() method, dropped the constructor from interface/abstract
- Use the IoC container to resolve the classes (allow DI)
- In the UrlFetcher, return a Response object, drop the state from there, decode automatically
- In the UrlHelper, use the PSR-7 Uri methods (requires / in front though)
- In the tests, change blob method to create 3 arguments directly, using the argument unpacking feature to make it less code
- Add option to use actual message mocks (eg. the raw requests), so we can mock headers + content instead of just html if need be (for example the Gzip)
- Renamed rules -> Rules (more PSR-4 ish)

Only did 2 tests for now, to make an example before you disagree ;)

What do you think?

### CODE REVIEW

**Comment by barryvdh** [comment]
Updated the rest of the rules/tests. Few remarks:

 - getRaw from the Crawler isn't needed, since you have the reponse object
 - making absolute links isn't needed from links in the Crawler, when passing the current url you can call `->link()->getUri()` and it should be absolute.

**Comment by phanan** [comment]
Wow. It's almost like you've rewritten the entire app! From first look, all of the changes make absolute sense, but I'll need to make some time today to pull and really wrap my head around them. Thanks for the amazing PR!

**Comment by barryvdh** [comment]
I've renamed the rules dir back, so you can see the actual changes in the tests easier.

Also changed the Providers/facades. You use an alias (eg. `UrlHelper`) for your classes, but when using dependency injection, it's easier to use the actual class name. This way you can typehint the class you need, and it doesn't matter if you inject or use the facade.

**Comment by phanan** [comment]
I've added some very minor fixes and cleanups, and squashed/merged your commits in 14b743fd00690ea01a02cb77b3e27ad44d4b8d51, 7e263a1573c3a90016e0289efb0785ec3b485e7e, 456e8444e42504676b3e40221523cc9ae39466af, and 4f461ba1b434db29d40662aec195d4fd196c0821 (was trying to give as much credits as possible, hence 4 different commits). Thanks again, this is certainly no doubt of the best PR's I've ever received!

**Pull request closed without merging**
